#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FloatingActionButtonXamarin.Resource", IsApplication=false)]

namespace FloatingActionButtonXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f030000
			public static int fab_scale_down = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int fab_scale_up = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int fab_slide_in_from_left = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int fab_slide_in_from_right = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int fab_slide_out_to_left = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int fab_slide_out_to_right = 2130903045;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public static int fab_colorDisabled = 2130771974;
			
			// aapt resource value: 0x7f010004
			public static int fab_colorNormal = 2130771972;
			
			// aapt resource value: 0x7f010005
			public static int fab_colorPressed = 2130771973;
			
			// aapt resource value: 0x7f010007
			public static int fab_colorRipple = 2130771975;
			
			// aapt resource value: 0x7f010011
			public static int fab_elevationCompat = 2130771985;
			
			// aapt resource value: 0x7f01000f
			public static int fab_hideAnimation = 2130771983;
			
			// aapt resource value: 0x7f010010
			public static int fab_label = 2130771984;
			
			// aapt resource value: 0x7f010016
			public static int fab_progress = 2130771990;
			
			// aapt resource value: 0x7f010013
			public static int fab_progress_backgroundColor = 2130771987;
			
			// aapt resource value: 0x7f010012
			public static int fab_progress_color = 2130771986;
			
			// aapt resource value: 0x7f010014
			public static int fab_progress_indeterminate = 2130771988;
			
			// aapt resource value: 0x7f010015
			public static int fab_progress_max = 2130771989;
			
			// aapt resource value: 0x7f010017
			public static int fab_progress_showBackground = 2130771991;
			
			// aapt resource value: 0x7f010009
			public static int fab_shadowColor = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public static int fab_shadowRadius = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public static int fab_shadowXOffset = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public static int fab_shadowYOffset = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public static int fab_showAnimation = 2130771982;
			
			// aapt resource value: 0x7f010008
			public static int fab_showShadow = 2130771976;
			
			// aapt resource value: 0x7f01000d
			public static int fab_size = 2130771981;
			
			// aapt resource value: 0x7f010000
			public static int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f01002b
			public static int menu_animationDelayPerItem = 2130772011;
			
			// aapt resource value: 0x7f01003b
			public static int menu_backgroundColor = 2130772027;
			
			// aapt resource value: 0x7f010019
			public static int menu_buttonSpacing = 2130771993;
			
			// aapt resource value: 0x7f01002c
			public static int menu_buttonToggleAnimation = 2130772012;
			
			// aapt resource value: 0x7f010037
			public static int menu_colorNormal = 2130772023;
			
			// aapt resource value: 0x7f010038
			public static int menu_colorPressed = 2130772024;
			
			// aapt resource value: 0x7f010039
			public static int menu_colorRipple = 2130772025;
			
			// aapt resource value: 0x7f01003e
			public static int menu_fab_hide_animation = 2130772030;
			
			// aapt resource value: 0x7f01003c
			public static int menu_fab_label = 2130772028;
			
			// aapt resource value: 0x7f01003d
			public static int menu_fab_show_animation = 2130772029;
			
			// aapt resource value: 0x7f010030
			public static int menu_fab_size = 2130772016;
			
			// aapt resource value: 0x7f01002a
			public static int menu_icon = 2130772010;
			
			// aapt resource value: 0x7f010026
			public static int menu_labels_colorNormal = 2130772006;
			
			// aapt resource value: 0x7f010027
			public static int menu_labels_colorPressed = 2130772007;
			
			// aapt resource value: 0x7f010028
			public static int menu_labels_colorRipple = 2130772008;
			
			// aapt resource value: 0x7f010024
			public static int menu_labels_cornerRadius = 2130772004;
			
			// aapt resource value: 0x7f010032
			public static int menu_labels_customFont = 2130772018;
			
			// aapt resource value: 0x7f01002e
			public static int menu_labels_ellipsize = 2130772014;
			
			// aapt resource value: 0x7f01001c
			public static int menu_labels_hideAnimation = 2130771996;
			
			// aapt resource value: 0x7f01001a
			public static int menu_labels_margin = 2130771994;
			
			// aapt resource value: 0x7f01002f
			public static int menu_labels_maxLines = 2130772015;
			
			// aapt resource value: 0x7f010021
			public static int menu_labels_padding = 2130772001;
			
			// aapt resource value: 0x7f010020
			public static int menu_labels_paddingBottom = 2130772000;
			
			// aapt resource value: 0x7f01001e
			public static int menu_labels_paddingLeft = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public static int menu_labels_paddingRight = 2130771999;
			
			// aapt resource value: 0x7f01001d
			public static int menu_labels_paddingTop = 2130771997;
			
			// aapt resource value: 0x7f010029
			public static int menu_labels_position = 2130772009;
			
			// aapt resource value: 0x7f01001b
			public static int menu_labels_showAnimation = 2130771995;
			
			// aapt resource value: 0x7f010025
			public static int menu_labels_showShadow = 2130772005;
			
			// aapt resource value: 0x7f01002d
			public static int menu_labels_singleLine = 2130772013;
			
			// aapt resource value: 0x7f010031
			public static int menu_labels_style = 2130772017;
			
			// aapt resource value: 0x7f010022
			public static int menu_labels_textColor = 2130772002;
			
			// aapt resource value: 0x7f010023
			public static int menu_labels_textSize = 2130772003;
			
			// aapt resource value: 0x7f01003a
			public static int menu_openDirection = 2130772026;
			
			// aapt resource value: 0x7f010033
			public static int menu_shadowColor = 2130772019;
			
			// aapt resource value: 0x7f010034
			public static int menu_shadowRadius = 2130772020;
			
			// aapt resource value: 0x7f010035
			public static int menu_shadowXOffset = 2130772021;
			
			// aapt resource value: 0x7f010036
			public static int menu_shadowYOffset = 2130772022;
			
			// aapt resource value: 0x7f010018
			public static int menu_showShadow = 2130771992;
			
			// aapt resource value: 0x7f010002
			public static int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public static int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public static int fab_size_mini = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int fab_size_normal = 2130968580;
			
			// aapt resource value: 0x7f040000
			public static int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			// aapt resource value: 0x7f040005
			public static int labels_text_size = 2130968581;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int fab_add = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public static int down = 2131034123;
			
			// aapt resource value: 0x7f050006
			public static int end = 2131034118;
			
			// aapt resource value: 0x7f050001
			public static int fab_label = 2131034113;
			
			// aapt resource value: 0x7f050000
			public static int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050004
			public static int left = 2131034116;
			
			// aapt resource value: 0x7f050007
			public static int marquee = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int middle = 2131034120;
			
			// aapt resource value: 0x7f050002
			public static int mini = 2131034114;
			
			// aapt resource value: 0x7f050009
			public static int none = 2131034121;
			
			// aapt resource value: 0x7f050003
			public static int normal = 2131034115;
			
			// aapt resource value: 0x7f050005
			public static int right = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public static int start = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public static int up = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public static int library_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[]
			{
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991};
			
			// aapt resource value: 2
			public static int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 0
			public static int FloatingActionButton_fab_colorNormal = 0;
			
			// aapt resource value: 1
			public static int FloatingActionButton_fab_colorPressed = 1;
			
			// aapt resource value: 3
			public static int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 13
			public static int FloatingActionButton_fab_elevationCompat = 13;
			
			// aapt resource value: 11
			public static int FloatingActionButton_fab_hideAnimation = 11;
			
			// aapt resource value: 12
			public static int FloatingActionButton_fab_label = 12;
			
			// aapt resource value: 18
			public static int FloatingActionButton_fab_progress = 18;
			
			// aapt resource value: 15
			public static int FloatingActionButton_fab_progress_backgroundColor = 15;
			
			// aapt resource value: 14
			public static int FloatingActionButton_fab_progress_color = 14;
			
			// aapt resource value: 16
			public static int FloatingActionButton_fab_progress_indeterminate = 16;
			
			// aapt resource value: 17
			public static int FloatingActionButton_fab_progress_max = 17;
			
			// aapt resource value: 19
			public static int FloatingActionButton_fab_progress_showBackground = 19;
			
			// aapt resource value: 5
			public static int FloatingActionButton_fab_shadowColor = 5;
			
			// aapt resource value: 6
			public static int FloatingActionButton_fab_shadowRadius = 6;
			
			// aapt resource value: 7
			public static int FloatingActionButton_fab_shadowXOffset = 7;
			
			// aapt resource value: 8
			public static int FloatingActionButton_fab_shadowYOffset = 8;
			
			// aapt resource value: 10
			public static int FloatingActionButton_fab_showAnimation = 10;
			
			// aapt resource value: 4
			public static int FloatingActionButton_fab_showShadow = 4;
			
			// aapt resource value: 9
			public static int FloatingActionButton_fab_size = 9;
			
			public static int[] FloatingActionMenu = new int[]
			{
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030};
			
			// aapt resource value: 19
			public static int FloatingActionMenu_menu_animationDelayPerItem = 19;
			
			// aapt resource value: 35
			public static int FloatingActionMenu_menu_backgroundColor = 35;
			
			// aapt resource value: 1
			public static int FloatingActionMenu_menu_buttonSpacing = 1;
			
			// aapt resource value: 20
			public static int FloatingActionMenu_menu_buttonToggleAnimation = 20;
			
			// aapt resource value: 31
			public static int FloatingActionMenu_menu_colorNormal = 31;
			
			// aapt resource value: 32
			public static int FloatingActionMenu_menu_colorPressed = 32;
			
			// aapt resource value: 33
			public static int FloatingActionMenu_menu_colorRipple = 33;
			
			// aapt resource value: 38
			public static int FloatingActionMenu_menu_fab_hide_animation = 38;
			
			// aapt resource value: 36
			public static int FloatingActionMenu_menu_fab_label = 36;
			
			// aapt resource value: 37
			public static int FloatingActionMenu_menu_fab_show_animation = 37;
			
			// aapt resource value: 24
			public static int FloatingActionMenu_menu_fab_size = 24;
			
			// aapt resource value: 18
			public static int FloatingActionMenu_menu_icon = 18;
			
			// aapt resource value: 14
			public static int FloatingActionMenu_menu_labels_colorNormal = 14;
			
			// aapt resource value: 15
			public static int FloatingActionMenu_menu_labels_colorPressed = 15;
			
			// aapt resource value: 16
			public static int FloatingActionMenu_menu_labels_colorRipple = 16;
			
			// aapt resource value: 12
			public static int FloatingActionMenu_menu_labels_cornerRadius = 12;
			
			// aapt resource value: 26
			public static int FloatingActionMenu_menu_labels_customFont = 26;
			
			// aapt resource value: 22
			public static int FloatingActionMenu_menu_labels_ellipsize = 22;
			
			// aapt resource value: 4
			public static int FloatingActionMenu_menu_labels_hideAnimation = 4;
			
			// aapt resource value: 2
			public static int FloatingActionMenu_menu_labels_margin = 2;
			
			// aapt resource value: 23
			public static int FloatingActionMenu_menu_labels_maxLines = 23;
			
			// aapt resource value: 9
			public static int FloatingActionMenu_menu_labels_padding = 9;
			
			// aapt resource value: 8
			public static int FloatingActionMenu_menu_labels_paddingBottom = 8;
			
			// aapt resource value: 6
			public static int FloatingActionMenu_menu_labels_paddingLeft = 6;
			
			// aapt resource value: 7
			public static int FloatingActionMenu_menu_labels_paddingRight = 7;
			
			// aapt resource value: 5
			public static int FloatingActionMenu_menu_labels_paddingTop = 5;
			
			// aapt resource value: 17
			public static int FloatingActionMenu_menu_labels_position = 17;
			
			// aapt resource value: 3
			public static int FloatingActionMenu_menu_labels_showAnimation = 3;
			
			// aapt resource value: 13
			public static int FloatingActionMenu_menu_labels_showShadow = 13;
			
			// aapt resource value: 21
			public static int FloatingActionMenu_menu_labels_singleLine = 21;
			
			// aapt resource value: 25
			public static int FloatingActionMenu_menu_labels_style = 25;
			
			// aapt resource value: 10
			public static int FloatingActionMenu_menu_labels_textColor = 10;
			
			// aapt resource value: 11
			public static int FloatingActionMenu_menu_labels_textSize = 11;
			
			// aapt resource value: 34
			public static int FloatingActionMenu_menu_openDirection = 34;
			
			// aapt resource value: 27
			public static int FloatingActionMenu_menu_shadowColor = 27;
			
			// aapt resource value: 28
			public static int FloatingActionMenu_menu_shadowRadius = 28;
			
			// aapt resource value: 29
			public static int FloatingActionMenu_menu_shadowXOffset = 29;
			
			// aapt resource value: 30
			public static int FloatingActionMenu_menu_shadowYOffset = 30;
			
			// aapt resource value: 0
			public static int FloatingActionMenu_menu_showShadow = 0;
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public static int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public static int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public static int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public static int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public static int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public static int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
